In [1]:
import numpy as np

## Comparing performance with lists, etc.

In [2]:
N = 100000000

In [ ]:
%%time
list_ = list(range(N))
for i in range(N):
    list_[i] = list_[i] * list_[i]

In [ ]:
%%time
list_ = list(range(N))
list_ = [item * item for item in list_]

In [ ]:
%%time
list_ = list(range(N))
list_ = map(lambda x: x * x, list_)

In [ ]:
%%time
list_ = list(range(N))
list_sum = 0
for item in list_:
    list_sum += item

In [ ]:
%%time
list_ = list(range(N))
list_sum = sum(list_)

In [3]:
%%time
arr = np.arange(N)
arr = arr * arr

Wall time: 371 ms


In [4]:
%%time
arr = np.arange(N)
arr_sum = np.sum(arr)

Wall time: 260 ms


# Creating np Arrays

In [5]:
arr = np.arange(5)

In [6]:
print(arr, type(arr))

[0 1 2 3 4] <class 'numpy.ndarray'>


In [7]:
arr = np.array([0.0, 2, 4, 6, 8])

In [8]:
print(arr, type(arr))

[0. 2. 4. 6. 8.] <class 'numpy.ndarray'>


In [9]:
arr

array([0., 2., 4., 6., 8.])

In [10]:
arr.dtype

dtype('float64')

In [11]:
arr.ndim

1

In [12]:
arr.shape

(5,)

In [13]:
arr.size

5

In [14]:
arr.itemsize

8

In [15]:
arr2d = np.array([
                  [1, 2, 3], 
                  [4, 5, 6]
])

In [16]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
arr2d.ndim

2

In [18]:
arr2d.shape

(2, 3)

In [19]:
arr2d.size

6

In [20]:
arr3d = np.array([
                  [
                   [1, 2, 3],
                   [4, 5, 6]
                  ],
                  [
                   [7, 8, 9], 
                   [10, 11, 12]
                  ]
])

In [21]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
arr3d.shape

(2, 2, 3)

In [23]:
arr3d.ndim

3

In [24]:
arr3d.size

12

In [25]:
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [26]:
1729 * np.ones((2, 3, 4))

array([[[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]],

       [[1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.],
        [1729., 1729., 1729., 1729.]]])

In [27]:
np.zeros((2, 3, 4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [28]:
np.random.randn(2, 3)

array([[-0.19991401, -0.76510115, -0.36970437],
       [ 1.2224862 , -0.76968592, -0.74007198]])

In [29]:
np.random.rand(2, 3)

array([[0.23156708, 0.92190901, 0.57042764],
       [0.64463657, 0.29233424, 0.81152363]])

In [30]:
np.random.rand(10, 1)

array([[0.34050312],
       [0.27360484],
       [0.40983751],
       [0.27437578],
       [0.77419789],
       [0.23285257],
       [0.76329394],
       [0.43027656],
       [0.10817228],
       [0.5454093 ]])

In [31]:
np.random.randint(0, 100, (2, 3))

array([[91, 93, 76],
       [54, 58,  5]])

In [32]:
np.arange(7, 71, 7)

array([ 7, 14, 21, 28, 35, 42, 49, 56, 63, 70])

In [33]:
np.linspace(7, 70, 10)

array([ 7., 14., 21., 28., 35., 42., 49., 56., 63., 70.])

In [34]:
np.array([True, False, True, True])

array([ True, False,  True,  True])

In [35]:
str_arr = np.array(['1.4', '2.1', '1.1'])

In [36]:
arr = np.array(str_arr, dtype='float')

In [37]:
arr

array([1.4, 2.1, 1.1])

## indexing

In [38]:
arr3d = np.array([
                  [
                   [1, 2, 3],
                   [4, 5, 6]
                  ],
                  [
                   [7, 8, 9], 
                   [10, 11, 12]
                  ]
])

In [39]:
print(arr3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [40]:
arr3d[0, 0, 0]

1

In [41]:
arr3d[1, 0, 2]

9

In [42]:
i = 1
j = 0
k = 2
arr3d[i, j, k]

9

In [43]:
arr3d[1, :, :]

array([[ 7,  8,  9],
       [10, 11, 12]])

In [44]:
arr3d[:, 1, :]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [45]:
arr3d[:, :, 0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [46]:
arr3d % 2 == 0

array([[[False,  True, False],
        [ True, False,  True]],

       [[False,  True, False],
        [ True, False,  True]]])

In [47]:
arr3d[arr3d % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

In [48]:
arr3d[(arr3d % 2 == 1) & (arr3d > 3)]

array([ 5,  7,  9, 11])

In [49]:
arr_slice = arr3d[:, :, 0:2]

In [50]:
print(type(arr_slice))

<class 'numpy.ndarray'>


In [51]:
arr_slice.ndim

3

In [52]:
arr_slice.shape

(2, 2, 2)

In [53]:
arr_slice[0, 0, 1]

2

In [54]:
arr_slice[0, 0, 0] = 1729

In [55]:
arr_slice

array([[[1729,    2],
        [   4,    5]],

       [[   7,    8],
        [  10,   11]]])

In [56]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [57]:
arr_slice = np.copy(arr3d[:, :, 0:2])

In [58]:
arr_slice[0, 0, 0] = 1

In [59]:
arr_slice

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [70]:
arr3d

array([[[1729,    2,    3],
        [   4,    5,    6]],

       [[   7,    8,    9],
        [  10,   11,   12]]])

In [71]:
arr = np.random.randint(0, 10, (5))

In [72]:
arr

array([4, 4, 0, 5, 4])

In [73]:
my_indices = [1, 3, 4]

In [74]:
arr[my_indices]

array([4, 5, 4])

# Numpy Operations

In [75]:
arr1 = np.random.rand(3, 4)
arr2 = np.random.rand(3, 4)

In [76]:
arr1

array([[0.28070723, 0.39766206, 0.17954339, 0.98667079],
       [0.43874284, 0.52037897, 0.26521069, 0.5277147 ],
       [0.30682295, 0.77133555, 0.99676419, 0.1086997 ]])

In [77]:
arr2

array([[0.53482865, 0.77166749, 0.84613542, 0.80711873],
       [0.66457236, 0.65519782, 0.83621638, 0.18693768],
       [0.22193569, 0.64836536, 0.62000057, 0.99793016]])

In [78]:
arr1 + arr2

array([[0.81553588, 1.16932955, 1.02567881, 1.79378951],
       [1.1033152 , 1.17557679, 1.10142707, 0.71465238],
       [0.52875865, 1.41970091, 1.61676476, 1.10662986]])

In [79]:
arr1 - arr2

array([[-0.25412142, -0.37400543, -0.66659203,  0.17955206],
       [-0.22582953, -0.13481886, -0.5710057 ,  0.34077703],
       [ 0.08488726,  0.1229702 ,  0.37676361, -0.88923046]])

In [80]:
arr1 * arr2

array([[0.15013027, 0.30686288, 0.15191802, 0.79636047],
       [0.29157636, 0.34095117, 0.22177352, 0.09864976],
       [0.06809496, 0.50010725, 0.61799437, 0.10847471]])

In [81]:
arr1 / arr2

array([[0.52485451, 0.51532825, 0.21219226, 1.22246053],
       [0.66018821, 0.79423183, 0.31715557, 2.82294458],
       [1.38248584, 1.18966189, 1.60768268, 0.10892516]])

In [82]:
np.exp(arr1)

array([[1.3240659 , 1.48834097, 1.19667082, 2.68228968],
       [1.55075644, 1.6826652 , 1.30370562, 1.69505418],
       [1.35910032, 2.16265266, 2.70950019, 1.11482752]])

In [83]:
np.log(np.exp(arr1))

array([[0.28070723, 0.39766206, 0.17954339, 0.98667079],
       [0.43874284, 0.52037897, 0.26521069, 0.5277147 ],
       [0.30682295, 0.77133555, 0.99676419, 0.1086997 ]])

In [84]:
np.sin(arr1)

array([[0.27703527, 0.38726389, 0.17858032, 0.83419464],
       [0.42480171, 0.49720898, 0.2621126 , 0.50356025],
       [0.30203149, 0.69709343, 0.83971826, 0.10848577]])

In [85]:
np.cos(arr1)

array([[0.96085975, 0.92196891, 0.98392534, 0.55147012],
       [0.90528642, 0.86763082, 0.9650373 , 0.86396011],
       [0.95329795, 0.7169803 , 0.54302232, 0.994098  ]])

In [86]:
np.sqrt(arr1)

array([[0.52981811, 0.63060452, 0.4237256 , 0.99331304],
       [0.66237666, 0.72137297, 0.5149861 , 0.72643974],
       [0.55391602, 0.87825711, 0.99838078, 0.32969638]])

In [87]:
arr_inv = 1 / arr1

In [88]:
arr_inv

array([[3.56243051, 2.51469804, 5.56968436, 1.01350928],
       [2.2792395 , 1.92167644, 3.7705871 , 1.89496331],
       [3.25920858, 1.29645262, 1.00324632, 9.19965723]])

In [89]:
arr1 = np.zeros((3, 5))

In [90]:
arr_inv = 1/arr1

<ipython-input-90-99c134ef9e18>:1: RuntimeWarning: divide by zero encountered in true_divide
  arr_inv = 1/arr1


In [91]:
print(arr_inv)

[[inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]


In [92]:
np.isinf(arr_inv[0,0])

True

In [93]:
np.isinf(arr_inv)

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# Broadcasting

In [94]:
arr1 = np.arange(6)

In [95]:
arr1.shape

(6,)

In [96]:
arr1

array([0, 1, 2, 3, 4, 5])

In [97]:
arr1 = arr1.reshape((3, 2))

In [98]:
arr1.shape

(3, 2)

In [99]:
arr1

array([[0, 1],
       [2, 3],
       [4, 5]])

In [100]:
arr2 = np.arange(6).reshape((3, 2))

In [101]:
arr1 + arr2

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [102]:
arr2[0].reshape((1, 2))

array([[0, 1]])

In [103]:
arr1 + arr2[0].reshape((1, 2)) # (3, 2) + (1, 2)

array([[0, 2],
       [2, 4],
       [4, 6]])

In [104]:
arr2[:, 0].reshape((3, 1))

array([[0],
       [2],
       [4]])

In [105]:
arr1 + arr2[:, 0].reshape((3, 1)) # (3, 2) + (3, 1)

array([[0, 1],
       [4, 5],
       [8, 9]])

In [106]:
arr1 + 1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [107]:
arr1 = np.arange(24).reshape((2, 3, 4))

In [108]:
arr1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [109]:
arr2 = np.ones((1, 4))

In [110]:
arr1 + arr2   # (2, 3, 4) + (1, 4)

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]])

In [111]:
arr1 = np.arange(4)

In [112]:
arr2 = np.arange(5)

In [113]:
print(arr1.shape, arr2.shape)

(4,) (5,)


In [114]:
arr1 + arr2

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [116]:
arr1.reshape(4, 1) + arr2  # (4, 1) + (5)

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [117]:
arr = np.random.rand(3, 3)

In [118]:
arr

array([[0.58947009, 0.09277912, 0.84386622],
       [0.75273332, 0.18937703, 0.67476162],
       [0.39145441, 0.44927494, 0.06910761]])

In [119]:
arr.T

array([[0.58947009, 0.75273332, 0.39145441],
       [0.09277912, 0.18937703, 0.44927494],
       [0.84386622, 0.67476162, 0.06910761]])

# File handling

In [120]:
planets_small = np.loadtxt("planets_small.txt")

ValueError: could not convert string to float: 'MERCURY'

In [121]:
planets_small = np.loadtxt("planets_small.txt", 
                           skiprows = 1)

ValueError: could not convert string to float: 'Mass'

In [122]:
planets_small = np.loadtxt("planets_small.txt", 
                           skiprows = 1,
                           usecols = (1, 2, 3, 4, 5, 6, 7, 8, 9))

In [123]:
planets_small

array([[3.3000e-01, 4.8700e+00, 5.9700e+00, 6.4200e-01, 1.8980e+03,
        5.6800e+02, 8.6800e+01, 1.0200e+02, 1.4600e-02],
       [5.7900e+01, 1.0820e+02, 1.4960e+02, 2.2790e+02, 7.7860e+02,
        1.4335e+03, 2.8725e+03, 4.4951e+03, 5.9064e+03],
       [4.2226e+03, 2.8020e+03, 2.4000e+01, 2.4700e+01, 9.9000e+00,
        1.0700e+01, 1.7200e+01, 1.6100e+01, 1.5330e+02]])

In [124]:
planets_small.shape

(3, 9)

In [125]:
planets = np.loadtxt("planets.txt", 
                           skiprows = 1,
                           usecols = (1, 2, 3, 4, 5, 6, 7, 8, 9))

ValueError: could not convert string to float: 'Unknown'

In [126]:
planets = np.genfromtxt("planets.txt", 
                        skip_header=1, 
                        usecols = [1, 2, 3, 4, 5, 6, 7, 8, 9])

In [127]:
planets

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [128]:
planets.shape

(20, 9)

In [129]:
np.isnan(planets)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, 

In [130]:
planets_new = np.nan_to_num(planets, nan=-1)

In [131]:
planets_new

array([[ 3.30000e-01,  4.87000e+00,  5.97000e+00,  7.30000e-02,
         6.42000e-01,  1.89800e+03,  5.68000e+02,  8.68000e+01,
         1.02000e+02],
       [ 4.87900e+03,  1.21040e+04,  1.27560e+04,  3.47500e+03,
         6.79200e+03,  1.42984e+05,  1.20536e+05,  5.11180e+04,
         4.95280e+04],
       [ 5.42700e+03,  5.24300e+03,  5.51400e+03,  3.34000e+03,
         3.93300e+03,  1.32600e+03,  6.87000e+02,  1.27100e+03,
         1.63800e+03],
       [ 3.70000e+00,  8.90000e+00,  9.80000e+00,  1.60000e+00,
         3.70000e+00,  2.31000e+01,  9.00000e+00,  8.70000e+00,
         1.10000e+01],
       [ 4.30000e+00,  1.04000e+01,  1.12000e+01,  2.40000e+00,
         5.00000e+00,  5.95000e+01,  3.55000e+01,  2.13000e+01,
         2.35000e+01],
       [ 1.40760e+03, -5.83250e+03,  2.39000e+01,  6.55700e+02,
         2.46000e+01,  9.90000e+00,  1.07000e+01, -1.72000e+01,
         1.61000e+01],
       [ 4.22260e+03,  2.80200e+03,  2.40000e+01,  7.08700e+02,
         2.47000e+01,  9.90000

In [132]:
np.savetxt('planets_new.txt', planets_new, 
           delimiter=',')

In [133]:
np.save("planets_new", planets_new)

In [134]:
!ls -lh

total 169K
-rw-r--r-- 1 KIIT None  66K Aug  4 10:17 FDS_W08_Lecture_NB-200320-184141.ipynb
-rw-r--r-- 1 KIIT None  51K Aug 23  2020 FDS_W08_Solutions-200320-184141.ipynb
-rw-r--r-- 1 KIIT None  23K Aug 23  2020 Numpy_Assignment_Solutions-200320-184846.ipynb
-rw-r--r-- 1 KIIT None 3.0K Aug 23  2020 Numpy_Assignments_Questions-200320-184846.ipynb
-rw-r--r-- 1 KIIT None 2.9K Aug 13  2020 cric_data-200320-181217.tsv
-rw-r--r-- 1 KIIT None 1.5K Aug 13  2020 planets.txt
-rw-r--r-- 1 KIIT None 1.6K Aug  4 10:25 planets_new.npy
-rw-r--r-- 1 KIIT None 4.5K Aug  4 10:25 planets_new.txt
-rw-r--r-- 1 KIIT None  257 Aug 13  2020 planets_small.txt


In [135]:
arr1 = np.random.rand(1000, 10)
arr2 = np.random.rand(2000, 5)
arr3 = np.random.rand(20, 10000)

In [136]:
np.savez("many_arrs", arr1, arr2, arr3)

In [137]:
!ls -lh

total 1.9M
-rw-r--r-- 1 KIIT None  66K Aug  4 10:17 FDS_W08_Lecture_NB-200320-184141.ipynb
-rw-r--r-- 1 KIIT None  51K Aug 23  2020 FDS_W08_Solutions-200320-184141.ipynb
-rw-r--r-- 1 KIIT None  23K Aug 23  2020 Numpy_Assignment_Solutions-200320-184846.ipynb
-rw-r--r-- 1 KIIT None 3.0K Aug 23  2020 Numpy_Assignments_Questions-200320-184846.ipynb
-rw-r--r-- 1 KIIT None 2.9K Aug 13  2020 cric_data-200320-181217.tsv
-rw-r--r-- 1 KIIT None 1.7M Aug  4 10:25 many_arrs.npz
-rw-r--r-- 1 KIIT None 1.5K Aug 13  2020 planets.txt
-rw-r--r-- 1 KIIT None 1.6K Aug  4 10:25 planets_new.npy
-rw-r--r-- 1 KIIT None 4.5K Aug  4 10:25 planets_new.txt
-rw-r--r-- 1 KIIT None  257 Aug 13  2020 planets_small.txt


In [138]:
arrs = np.load('many_arrs.npz')

In [139]:
print(type(arrs))

<class 'numpy.lib.npyio.NpzFile'>


In [140]:
arrs.files

['arr_0', 'arr_1', 'arr_2']

In [141]:
arrs['arr_0'].shape

(1000, 10)

In [142]:
np.savez_compressed('many_arrs_compressed', 
                    arr1, arr2, arr3)

In [143]:
!ls -lh

total 3.5M
-rw-r--r-- 1 KIIT None  66K Aug  4 10:17 FDS_W08_Lecture_NB-200320-184141.ipynb
-rw-r--r-- 1 KIIT None  51K Aug 23  2020 FDS_W08_Solutions-200320-184141.ipynb
-rw-r--r-- 1 KIIT None  23K Aug 23  2020 Numpy_Assignment_Solutions-200320-184846.ipynb
-rw-r--r-- 1 KIIT None 3.0K Aug 23  2020 Numpy_Assignments_Questions-200320-184846.ipynb
-rw-r--r-- 1 KIIT None 2.9K Aug 13  2020 cric_data-200320-181217.tsv
-rw-r--r-- 1 KIIT None 1.7M Aug  4 10:25 many_arrs.npz
-rw-r--r-- 1 KIIT None 1.6M Aug  4 10:25 many_arrs_compressed.npz
-rw-r--r-- 1 KIIT None 1.5K Aug 13  2020 planets.txt
-rw-r--r-- 1 KIIT None 1.6K Aug  4 10:25 planets_new.npy
-rw-r--r-- 1 KIIT None 4.5K Aug  4 10:25 planets_new.txt
-rw-r--r-- 1 KIIT None  257 Aug 13  2020 planets_small.txt


In [144]:
arr1 = np.zeros((10000, 10000))

In [145]:
np.savez("zeros", arr1)

In [146]:
np.savez_compressed("zeros_compressed", arr1)

In [147]:
!ls -lh

total 768M
-rw-r--r-- 1 KIIT None  66K Aug  4 10:17 FDS_W08_Lecture_NB-200320-184141.ipynb
-rw-r--r-- 1 KIIT None  51K Aug 23  2020 FDS_W08_Solutions-200320-184141.ipynb
-rw-r--r-- 1 KIIT None  23K Aug 23  2020 Numpy_Assignment_Solutions-200320-184846.ipynb
-rw-r--r-- 1 KIIT None 3.0K Aug 23  2020 Numpy_Assignments_Questions-200320-184846.ipynb
-rw-r--r-- 1 KIIT None 2.9K Aug 13  2020 cric_data-200320-181217.tsv
-rw-r--r-- 1 KIIT None 1.7M Aug  4 10:25 many_arrs.npz
-rw-r--r-- 1 KIIT None 1.6M Aug  4 10:25 many_arrs_compressed.npz
-rw-r--r-- 1 KIIT None 1.5K Aug 13  2020 planets.txt
-rw-r--r-- 1 KIIT None 1.6K Aug  4 10:25 planets_new.npy
-rw-r--r-- 1 KIIT None 4.5K Aug  4 10:25 planets_new.txt
-rw-r--r-- 1 KIIT None  257 Aug 13  2020 planets_small.txt
-rw-r--r-- 1 KIIT None 763M Aug  4 10:25 zeros.npz
-rw-r--r-- 1 KIIT None 760K Aug  4 10:25 zeros_compressed.npz


# Stats with NumPy

In [148]:
arr = np.random.rand(10000000,)

In [149]:
np.amin(arr)

4.534931496991135e-08

In [150]:
np.amax(arr)

0.9999999642806386

In [151]:
np.mean(arr)

0.4999500939169886

In [152]:
np.var(arr)

0.0832996248526235

In [153]:
np.std(arr)

0.28861674388819425

In [154]:
np.median(arr)

0.49980617588716253

In [155]:
np.percentile(arr, 50)

0.49980617588716253

In [156]:
np.percentile(arr, 10)

0.100086868611581

In [157]:
np.percentile(arr, 90)

0.8999602483028822

In [158]:
%%time
iqr = np.percentile(arr, 75) - np.percentile(arr, 25)

Wall time: 283 ms


In [159]:
print(iqr)

0.49978190662496214


In [160]:
%%time
quartiles = np.percentile(arr, [25, 75])
iqr = quartiles[1] - quartiles[0]

Wall time: 189 ms


In [161]:
print(quartiles)

[0.25009436 0.74987626]


In [162]:
print(iqr)

0.49978190662496214


In [163]:
(arr - np.mean(arr))/np.std(arr)

array([ 0.77897948,  0.71984582, -1.33072281, ..., -1.22008735,
        1.36434697,  0.50187435])

In [164]:
np.histogram(arr)

(array([ 999152,  999720, 1000407, 1000757, 1001867, 1000507,  999180,
         998695, 1000074,  999641], dtype=int64),
 array([4.53493150e-08, 1.00000037e-01, 2.00000029e-01, 3.00000021e-01,
        4.00000013e-01, 5.00000005e-01, 5.99999997e-01, 6.99999989e-01,
        7.99999980e-01, 8.99999972e-01, 9.99999964e-01]))

In [165]:
np.histogram(arr, bins=5)

(array([1998872, 2001164, 2002374, 1997875, 1999715], dtype=int64),
 array([4.53493150e-08, 2.00000029e-01, 4.00000013e-01, 5.99999997e-01,
        7.99999980e-01, 9.99999964e-01]))

In [166]:
np.histogram(arr, bins=[0, 0.25, 0.5, 0.75, 1])

(array([2499092, 2502811, 2499320, 2498777], dtype=int64),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [167]:
bins = [0, 0.25, 0.5, 0.75, 1]

In [168]:
np.digitize(arr, bins)

array([3, 3, 1, ..., 1, 4, 3], dtype=int64)

In [169]:
arr1 = np.random.randint(0, 10, (10))

In [170]:
arr1

array([2, 1, 0, 3, 7, 0, 0, 0, 6, 2])

In [171]:
bins = [0, 6, 10]

In [172]:
np.digitize(arr1, bins)

array([1, 1, 1, 1, 2, 1, 1, 1, 2, 1], dtype=int64)

In [173]:
np.digitize(arr1, bins, right=True)

array([1, 1, 0, 1, 2, 0, 0, 0, 1, 1], dtype=int64)

In [174]:
arr1 = np.random.randint(50, 80, 100) # weight

In [175]:
arr2 = np.random.randint(150, 185, 100) # heights

In [176]:
arr3 = np.random.randint(17, 22, 100) # age

In [177]:
np.concatenate((arr1, arr2, arr3)).shape

(300,)

In [178]:
np.vstack((arr1, arr2, arr3)).shape

(3, 100)

In [179]:
arr2d = np.vstack((arr1, arr2, arr3))

In [180]:
np.amin(arr2d, axis=1)

array([ 50, 150,  17])

In [181]:
np.amax(arr2d, axis=1)

array([ 79, 184,  21])

In [182]:
np.mean(arr2d, axis=1)

array([ 65.15, 165.38,  19.04])

# Checking stats rules with numpy

## Mean subracted array has zero mean

In [183]:
arr = np.random.rand(1000)

In [184]:
mean = np.mean(arr)

In [185]:
arr1 = arr - mean

In [186]:
np.mean(arr1)

-4.085620730620576e-17

## Computing mean with smaller set of values

In [187]:
arr = np.random.rand(1000)

In [188]:
for k in range(1, 50):
    arr1 = arr[0:k]
    print(k, np.mean(arr1))

1 0.9305656730068212
2 0.5862201831917822
3 0.5388654005005982
4 0.5687335549895539
5 0.4572877825792473
6 0.48859207040250796
7 0.48047354037493467
8 0.4462193257333542
9 0.47243057051754317
10 0.5147152132605213
11 0.517382920702911
12 0.5164920278064411
13 0.5167496962366489
14 0.5047141951838287
15 0.5302866949224128
16 0.5137259014189371
17 0.5159581761830607
18 0.5289503341034241
19 0.5392490051328304
20 0.5242789168677222
21 0.5440112760078122
22 0.5588782077546098
23 0.5374450136124492
24 0.5476031035160935
25 0.5431423607464516
26 0.5274194857309111
27 0.5357661688786707
28 0.5337376059927035
29 0.5402740783287515
30 0.5269895053923339
31 0.5382051205634867
32 0.5422832037682754
33 0.5532969277631653
34 0.5627496123829179
35 0.5494657442404897
36 0.5394067643822957
37 0.5497859929718902
38 0.5488454181119612
39 0.5486100982585566
40 0.5417732871880216
41 0.5357151320021057
42 0.5369376544886095
43 0.5426035780302286
44 0.535419281623555
45 0.5365955103470867
46 0.5356717480934

In [189]:
np.cumsum?

In [190]:
means = np.cumsum(arr)/np.arange(1,1001)

In [191]:
means[0:15]

array([0.93056567, 0.58622018, 0.5388654 , 0.56873355, 0.45728778,
       0.48859207, 0.48047354, 0.44621933, 0.47243057, 0.51471521,
       0.51738292, 0.51649203, 0.5167497 , 0.5047142 , 0.53028669])

## Effect of outliers on mean and median

In [192]:
arr = np.random.randint(1, 100, 100)

In [193]:
np.mean(arr)

52.6

In [194]:
np.median(arr)

54.5

In [195]:
arr = np.append(arr, [1000, 2000])

In [196]:
arr.shape

(102,)

In [197]:
np.mean(arr)

80.98039215686275

In [198]:
np.median(arr)

56.0

## Effect of scaling arrays on mean and median

In [199]:
arr = np.random.rand(100)

In [200]:
np.mean(arr)

0.47738945119336795

In [201]:
np.median(arr)

0.44835744775513375

In [202]:
arr1 = 2.5 * arr + 0.65

In [203]:
print(np.mean(2.5 * arr + 0.65), 
      2.5 * np.mean(arr) + 0.65)

1.8434736279834198 1.8434736279834198


In [204]:
print(np.median(2.5 * arr + 0.65), 
      2.5 * np.median(arr) + 0.65)

1.7708936193878344 1.7708936193878344


In [205]:
print(np.var(2.5 * arr + 0.65), 
      2.5*2.5*np.var(arr))

0.5307126613553003 0.5307126613553005


In [206]:
print(np.std(2.5 * arr + 0.65), 
      2.5 * np.std(arr))

0.7285002823302817 0.728500282330282


In [207]:
arr1 = np.random.rand(100)
arr2 = np.random.rand(100)

In [208]:
print( np.mean(0.21 * arr1 - 0.75 * arr2), 
      0.21 * np.mean(arr1) - 0.75 * np.mean(arr2))

-0.2553363417312178 -0.2553363417312178
